// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytifnbzujkkmyzwmplff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aWZuYnp1amtrbXl6d21wbGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjMzMDcsImV4cCI6MjA1NzkzOTMwN30.TD3BDv1ftcqfcfgRZ5fcq_rURHRanYQ268pNib9kztI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);